
const mongoose=require("mongoose");
const userSchema=new mongoose.Schema(
    {
        first_name:{
            type:String,
            required:true,
            trim:true
        },
        last_name:{
            type:String,
            required:true,
            trim:true
        },
        email:{
            type:String,
            required:true,
            trim:true
        },
        password:{
            type:String,
            required:true,
            
        },
        confirmPassword:{
            type:String,
            required:true,
        },
        accountType:{
            type:String,
            required:true,
            enum:["Admin","Student","Instructor"]
        },
        additionalDetails:{
            type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:"Profile"
        },
        courses:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"Courses"
            }
        ],
        courseProgress:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"CourseProgress"
            }
        ],
        token:{
            type:String,
        },
        ResetPasswordExpires:{
            type:Date
        },
        image:{
            type:String,
            required:true
        }
    }
)
module.exports=mongoose.model("User",userSchema);
